name: main

on: [push]

env:
  BASE_URL: gl-experiments

jobs:
  main:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      - run: bunx vite build packages/app --base $BASE_URL --minify false --outDir ../../dist

      - run: |
          for FILE in $( cd packages ; find demo -maxdepth 1 -type d -not -name node_modules -not -name demo)
          do
            bunx vite build packages/$FILE --base $BASE_URL/$FILE --minify false --outDir ../../../dist/$FILE
          done

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'

      - run: bun test

      - run: bun fmt

      - run: bun type

      # - run: bunx biome check .
