name: main

on: [push]

env:
  BASE_URL: gl-experiments

jobs:
  main:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      - run: bunx vite build packages/app --base $BASE_URL --minify false --outDir ../../dist

      - run: bunx vite build packages/demo/intSampler --base $BASE_URL/demo-int-sampler --minify false --outDir ../../../dist/demo-int-sampler

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'

      - run: bun test

      # - run: bunx biome check .

      - run: bunx tsc --noEmit
